# Generated by Django 4.1.4 on 2023-01-07 02:13

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Domain',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('photo', models.ImageField(upload_to='photos/domain/')),
                ('is_active', models.BooleanField(default=False)),
                ('modified_date', models.DateTimeField(default=datetime.datetime.now)),
                ('created_date', models.DateTimeField(default=datetime.datetime.now)),
            ],
        ),
        migrations.CreateModel(
            name='Member',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('photo', models.ImageField(upload_to='photos/domain/members/')),
                ('role', models.CharField(max_length=150)),
                ('instagram', models.CharField(max_length=200)),
                ('linkedin', models.CharField(max_length=200)),
                ('mail_id', models.EmailField(max_length=254)),
                ('github', models.CharField(max_length=250)),
                ('is_active', models.BooleanField(default=False)),
                ('modified_date', models.DateTimeField(default=datetime.datetime.now)),
                ('created_date', models.DateTimeField(default=datetime.datetime.now)),
                ('domain', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='teams.domain')),
            ],
        ),
    ]
