# Generated by Django 4.1.4 on 2023-01-08 07:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0002_remove_member_role_member_is_co_lead_member_is_coord_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='member',
            old_name='is_co_lead',
            new_name='is_colead',
        ),
    ]
