# Generated by Django 4.1.4 on 2023-01-09 19:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0003_rename_is_co_lead_member_is_colead'),
    ]

    operations = [
        migrations.AddField(
            model_name='domain',
            name='slug',
            field=models.SlugField(blank=True),
        ),
    ]
