# Generated by Django 4.1.4 on 2023-01-09 19:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0004_domain_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='domain',
            name='slug',
        ),
    ]
