# Generated by Django 4.1.4 on 2023-01-09 19:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0005_remove_domain_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='domain',
            name='slug',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='member',
            name='slug',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
