# Generated by Django 4.1.4 on 2023-01-09 19:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0006_domain_slug_member_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='domain',
            name='slug',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='member',
            name='slug',
            field=models.CharField(max_length=200),
        ),
    ]
