# Generated by Django 4.1.4 on 2023-01-09 20:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0008_rename_domain_member_title'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='domain',
            name='slug',
        ),
    ]
