# Generated by Django 4.1.4 on 2023-01-09 21:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='faq',
            name='answer',
            field=models.TextField(default='hello'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='faq',
            name='question',
            field=models.CharField(max_length=200),
        ),
    ]
